Добавлено Домашнее задание 1. Резиновый макет
sponfin/admin-panel-makeup pull request #2
Opened 2022-01-15 12:29 UTC by sponfin

Добрый день!

Хедер таблице, контентную часть в таблице и футер в таблице получилось сделать только отдельными блоками, пробовал обернуть все три части в единый блок, но не получилось. Переставал футер фиксироваться и все ломалось.

Так же пробовал добавлять иконки SVG. Пока так и не понял как лучше с ними работать, чтобы цвет их менять.
Пока остановился на свойстве filter.

2022-01-19 22:59 UTC, Muslik requested changes
Есть замечания

2022-01-19 22:59 UTC, Muslik commented on index.html
> +        <p>TABLE CONTENT</p>
Просьба делать все в рамках задания. На макете нет ни иконок, ни текста.

2022-01-19 22:59 UTC, Muslik commented on index.html
> +      <header class="header">
У header-а на макете есть background

2022-01-19 22:59 UTC, Muslik commented on style.css
> +  width: 1504px;
Макет должен тянуться на всю ширину экрана с некоторыми отступами по бокам

2022-01-19 22:59 UTC, Muslik commented on style.css
> +  /* height: 32px; */
Убрать ненужные комментарии

2022-01-19 22:59 UTC, Muslik commented on index.html
> +            <div class="buttton-header__load"></div>
Нет такого текста на макете

2022-01-19 22:59 UTC, Muslik commented on index.html
> +      <div class="table-header">Table Header</div>
Все таки таблица это единый блок состоящий из блока table и его детей - header, body, footer

2022-01-19 22:59 UTC, Muslik commented on index.html
> +      <div class="table-footer">Footer</div>
table-footer должен быть элементом блока table. Все таки без нее он не имеет никакого смысла.

2022-01-19 22:59 UTC, Muslik commented on index.html
> +          <div class="buttton-header">
buttton -> button

2022-01-20 05:25 UTC, sponfin commented on style.css
> +  width: 1504px;
В макете ширина указана 1504px; Или сделать, к примеру,  width: 95%?

2022-01-21 16:28 UTC, Muslik requested changes

2022-01-21 16:28 UTC, Muslik commented on index.html
> +          <p>TABLE CONTENT</p>
В макете нет этого

2022-01-21 16:28 UTC, Muslik commented on style.css
> +html,
Если я в вашу таблицу добавлю очень много контента, она не будет того вида какая должна быть. Тоже самое если удалю весь контент

2022-01-21 16:43 UTC, Muslik commented on index.html
> +    <!-- <meta http-equiv="Content-Type" content="application/xhtml+xml" /> -->
Ненужный код. Удалить

2022-01-21 17:37 UTC, Muslik approved these changes

2022-01-21 17:40 UTC, merged