Добавлено Домашнее задание 3. Верстка Input
sponfin/admin-panel-makeup pull request #5
Opened 2022-01-26 14:39 UTC by sponfin

Файлы размещены https://sponfin.github.io/admin-panel-makeup/

Джабраил, хочу дать комментарий по иконкам. Если я правильно понял, то мы верстали фактически один блок с двумя модификаторами (при ошибке и при блокировке инпута). Т.к. в дальнейшем наверно это должно выглядеть так, что при определенных условиях мы просто будем меняем или добавляем класс к элементу, то я не стал жестко прописывать иконки в html, а прописал их в CSS. Сделал через mask-image. Других способов, чтобы поменять цвет у SVG в CSS не нашел. Остальные способы предполагают жестко писать код SVG в HTML. Пробовал собрать все картинки в отдельный sprite, но тоже что-то не заработало.

2022-01-28 04:39 UTC, sponfin commented
Добрый день! Все же получилось добавлять иконки через один sprite. Плюс добавил границу у блока элементов, чтобы потом элементы из других ДЗ добавлять.

2022-01-29 18:11 UTC, Muslik requested changes
Прикреплю видео

2022-01-29 18:12 UTC, Muslik requested changes
Прикреплю видео

2022-01-29 21:22 UTC, sponfin commented
Ссылка на ui-kit [https://sponfin.github.io/admin-panel-makeup/pages/blocks/ui-kit.html](url)

Исправил разметку. Добавил блок label и input в один блок. Ему сделал внешние отступы снизу, у последнего бока отступы убрал. У обертки внутренние отступы сделал. id у label переименовал. Единственное что, label пришлось оставить в блоке div, иначе он отображался не сверху, а рядом с инпутом.

Не совсем понял, что делать с размерами самого инпута. Ты говорил, что они вроде как резиновыми не должны быть. Размеры я делал как в макете, т.е. фиксированные. Поэтому иконки имеют абсолютное позиционирование. Я так понял все так сделали. Или нужно делать, чтобы при изменении размера инпута иконки тоже сдвигались? Тогда абсолютное позиционирование не прокатит, правильно? Пока оставил как есть...

2022-01-30 05:26 UTC, sponfin commented
Ссылка на ui-kit [https://sponfin.github.io/admin-panel-makeup/pages/blocks/ui-kit.html](https://sponfin.github.io/admin-panel-makeup/pages/blocks/ui-kit.html)

В итоге сделал иконки в инпутах на флексах. Оставил размеры инпута как в макете, но теперь если меняются разменры инпута, позиционирование иконок не ломается.

2022-01-30 07:10 UTC, sponfin commented
Ссылка на ui-kit [https://sponfin.github.io/admin-panel-makeup/pages/blocks/ui-kit.html](https://sponfin.github.io/admin-panel-makeup/pages/blocks/ui-kit.html)

Изменил способ того, как убрать маржин у последнего элемента. Сначала сделал через обнуление маржина у last-child, но потом вспомнил, что можно было у последнего элемента просто убрать класс, который отвечает за его позиционирование.

2022-01-30 08:47 UTC, sponfin commented
Ссылка на ui-kit [https://sponfin.github.io/admin-panel-makeup/pages/blocks/ui-kit.html](https://sponfin.github.io/admin-panel-makeup/pages/blocks/ui-kit.html)

Все-таки убрал у лейбла обертку div. Сам label сделал блочным, все встало на свои места. Вроде теперь структура как ты показывал на видео. Один блок и в нем и label и input.

2022-02-01 21:05 UTC, Muslik requested changes
Немного замечаний

2022-02-01 21:05 UTC, Muslik commented on pages/blocks/ui-kit.html
> +        <div class="input-date block-wrapper__input-date">
Не нужен отдельный класс для margin-ов.
Есть псведокласс last-child. Вы можете input-date врубить margin-ы снизу всегда а у input-date:last-child отрубить

2022-02-01 21:05 UTC, Muslik commented on pages/blocks/ui-kit.html
> +              readonly
Поле должно быть disabled. Я сейчас могу фокус в инпут поставить.

2022-02-01 21:05 UTC, Muslik commented on pages/blocks/ui-kit.html
> +            <span class="input-date__btn">
Такое позиционирование не пойдет. (Я про margin-left: -18px)
Во первых это должно быть кнопка. И позиционировать нужно absolut-ом относительно родительской обертки

2022-02-02 06:17 UTC, sponfin commented on pages/blocks/ui-kit.html
> +              readonly
Исправил

2022-02-02 06:17 UTC, sponfin commented on pages/blocks/ui-kit.html
> +            <span class="input-date__btn">
Исправил

2022-02-02 06:19 UTC, sponfin commented on pages/blocks/ui-kit.html
> +        <div class="input-date block-wrapper__input-date">
Не совсем понял как без отдельного класса сделать маржины у input-date. input-date -это же блок, у него не должно быть маржинов вообще

2022-02-04 21:32 UTC, Muslik approved these changes
Хорошо

2022-02-05 06:21 UTC, merged