Добавлено Домашнее задание 4. Верстка Searchbar
sponfin/admin-panel-makeup pull request #6
Opened 2022-02-01 04:37 UTC by sponfin

Добавлено Домашнее задание 4. Верстка Searchbar

[https://sponfin.github.io/admin-panel-makeup/pages/blocks/ui-kit.html](https://sponfin.github.io/admin-panel-makeup/pages/blocks/ui-kit.html)

Ссылка пока настроена на ветку ДЗ_3. После апрува ДЗ_3 переключу на ветку с ДЗ_4

2022-02-01 06:34 UTC, sponfin commented
> Ссылка пока настроена на ветку ДЗ_3. После апрува ДЗ_3 переключу на ветку с ДЗ_4
Хотя переключил ссылку на ветку с ДЗ_4, она же включает в себя ДЗ_3

2022-02-01 21:10 UTC, Muslik requested changes
Есть замечания

2022-02-01 21:10 UTC, Muslik commented on pages/blocks/ui-kit.html
> +            <svg class="searchbar__icon-search">
позиционирование иконки сделано неверно. Ошибка такая же как в инпуте.

2022-02-01 21:10 UTC, Muslik commented on pages/blocks/ui-kit.html
> +        <div class="searchbar block-wrapper__searchbar">
Не нужен отдельный класс для margin. Используйте last-child

2022-02-01 21:10 UTC, Muslik commented on pages/blocks/ui-kit.html
> +            <span class="searchbar__btn">
Должно быть кнопкой. И позиционировать нужно будет кнопку, не иконку.

2022-02-02 06:21 UTC, sponfin commented
[https://sponfin.github.io/admin-panel-makeup/pages/blocks/ui-kit.html](https://sponfin.github.io/admin-panel-makeup/pages/blocks/ui-kit.html)

2022-02-04 21:34 UTC, Muslik approved these changes
Иконка поиска - это просто иконка. Не кнопка. :) Если исправишь, будет хорошо

2022-02-05 06:26 UTC, merged