Добавлено Домашнее задание 6. Верстка Dropdown
sponfin/admin-panel-makeup pull request #9
Opened 2022-02-07 13:36 UTC by sponfin

Добрый день!

[https://sponfin.github.io/admin-panel-makeup/pages/blocks/ui-kit.html](https://sponfin.github.io/admin-panel-makeup/pages/blocks/ui-kit.html)

2022-02-08 18:42 UTC, Muslik requested changes
Прошу прощения что сразу в дизайне этого не указали. Сейчас исправились. Второй блок ведет себя как radio список.

2022-02-08 21:58 UTC, Muslik approved these changes
Есть замечание по поводу селекторов

2022-02-08 21:58 UTC, Muslik commented on pages/blocks/dropdown.css
> +.dropdown .radio {
.dropdown - блок. .radio - блок. Отступ блокам задавать нельзя. Плюс Из за перечисления классов, ты им поднял специфичность. Поэтому нужен элемент: .dropdown__radio например

2022-02-09 04:35 UTC, sponfin commented on pages/blocks/dropdown.css
> +.dropdown .radio {
Исправил)

2022-02-09 04:36 UTC, merged